import {
  GraduationCap,
  TrendingUp,
  Palette,
  MessageCircle,
  ChefHat,
  Bike,
  Monitor,
  Landmark,
  Smartphone,
  Gamepad2,
  HeartPulse,
  PiggyBank,
  Crown,
  Factory,
  Music,
  Camera,
  Store,
  Building,
  Footprints,
  Plane,
  BarChart3,
  Handshake,
  Sprout,
  PenTool,
  Truck,
  Briefcase,
  Rocket,
  Megaphone,
  Volume2,
  Users,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

// Map from icon key (stored in data) → Lucide component
const ICON_MAP: Record<string, LucideIcon> = {
  "graduation-cap": GraduationCap,
  "trending-up": TrendingUp,
  palette: Palette,
  "message-circle": MessageCircle,
  "chef-hat": ChefHat,
  bike: Bike,
  monitor: Monitor,
  landmark: Landmark,
  smartphone: Smartphone,
  "gamepad-2": Gamepad2,
  "heart-pulse": HeartPulse,
  "piggy-bank": PiggyBank,
  crown: Crown,
  factory: Factory,
  music: Music,
  camera: Camera,
  store: Store,
  building: Building,
  footprints: Footprints,
  plane: Plane,
  "bar-chart-3": BarChart3,
  handshake: Handshake,
  sprout: Sprout,
  "pen-tool": PenTool,
  truck: Truck,
  briefcase: Briefcase,
  rocket: Rocket,
  megaphone: Megaphone,
  "volume-2": Volume2,
};

export function getSigIcon(iconKey?: string): LucideIcon {
  if (!iconKey) return Users;
  return ICON_MAP[iconKey] ?? Users;
}
